### ISSUE TITLE
Can't add subscription in channel preview

### ISSUE THREAD

**Issue by Markus-Fitz** [nilshellerhoff/abokistde#3]
Once in the channel overview, an subscription of the channel can't be added - the subscription can only be added from within the search.

**Comment by nilshellerhoff** [comment]
Oh no, that's really a big oversight! Will add ASAP

**Comment by nilshellerhoff** [comment]
@Markus-Fitz This has been fixed now. You can subscribe from the channel page, or manage your subscription if already subscribed:
![image](https://github.com/nilshellerhoff/abokistde/assets/24147614/587b9f53-fa8c-4f38-badb-1a27ac4d679b)
![image](https://github.com/nilshellerhoff/abokistde/assets/24147614/cd8a175e-7140-4163-9bb4-8fc026058483)
